### PR TITLE
[SIDE-1085] Publish LDK to NuGet

### PR DESCRIPTION
**Pull request by richseviora**
This PR updates the metadata and adds a publication action on new releases

@iangallOlive could you create an API key in NuGet for the Olive organization and add it as a GitHub actions secret as `NUGET_API_KEY`.

### CODE REVIEW

**Comment by iangallOlive** [comment]
@richseviora Yep, I'm on it

**Review by bbrewer-oliveai — APPROVED** [review]

**Comment by iangallOlive** [comment]
@richseviora I think it should be all set up. I created an API key in Nuget, scoped to the `oliveai` org, and added it as a GitHub Secret to the `open-olive` org (so all repos can use it).

**Review by iangallOlive — APPROVED** [review]

**Comment by iangallOlive** [comment]
@richseviora One thing I noticed in Nuget is that we can generate a certificate to our Nuget org, that allows us to sign the package (whatever that means). Just wanted to point it out, and see if you want/care to integrate that concept with this. Let me know if I can do anything for that

**Comment by richseviora** [comment]
Thanks for the prompt! I noticed that too but forgot to make a note of that.

So... I'm not sure how we can integrate package signing, the action I'm using doesn't seem to support that. It's something we should do, let me look into that

**Comment by richseviora** [comment]
SIDE-1169 has been created for package signing

**Pull request merged**
